spring:
  application:
    name: isu-app
  profiles:
    active: dev
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
    throw-exception-if-no-handler-found: true

feign:
  httpclient:
    disable-ssl-validation: true
    enabled: true
  okhttp:
    enabled: true
server:
  port: 8084



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/



